version: '3'
services:
  traefik:
    container_name: traefik
    image: traefik:latest
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
    ports:
      - 80:80
      - 443:443      
    environment:
      - CF_API_EMAIL=dwxxxxxxxxx@gmail.com
      - CF_API_KEY=1xxx626d3f32xxx7edc9xxxf4d8xxxx6fbf64
      - CF_DNS_API_TOKEN=DNS:hxxxiYVBvxxxc0pKxxxzVkte0xxF0z5_n
      - CF_ZONE_API_TOKEN=Zone:PaxxUhQmvxxxlZVDUzxxCMkxxgTb7_6   
      
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./data/traefik.yml:/traefik.yml:ro
      - ./data/acme.json:/acme.json
    labels:
     - "log.level=DEBUG"
     - "traefik.enable=true"
     - "traefik.http.routers.traefik.entrypoints=http"
     - "traefik.http.routers.traefik.rule=Host(`dash.xxxxxs.com`)"
     - "traefik.http.middlewares.traefik-auth.basicauth.users=admin:$$axxx$$a1xxOLUFxx9buGSp1"
     - "traefik.http.middlewares.traefik-https-redirect.redirectscheme.scheme=https"
     - "traefik.http.routers.traefik.middlewares=traefik-https-redirect"
     - "traefik.http.routers.traefik-secure.entrypoints=https"
     - "traefik.http.routers.traefik-secure.rule=Host(`dash.xxxxxs.com`)"
     - "traefik.http.routers.traefik-secure.middlewares=traefik-auth"
     - "traefik.http.routers.traefik-secure.tls=true"
     - "traefik.http.routers.traefik-secure.tls.certresolver=letsEncrypt"
     - "traefik.http.routers.traefik-secure.service=api@internal"
          
  portainer:
    image: portainer/portainer-ce:2.11.1
    container_name: portainer
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
    ports:
      - 9000      
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./data:/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.entrypoints=http"
      - "traefik.http.routers.portainer.rule=Host(`portainer.xxxxxs.com`)"
      - "traefik.http.middlewares.portainer-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.portainer.middlewares=portainer-https-redirect"
      - "traefik.http.routers.portainer-secure.entrypoints=https"
      - "traefik.http.routers.portainer-secure.rule=Host(`portainer.xxxxxs.com`)"
      - "traefik.http.routers.portainer-secure.tls=true"
      - "traefik.http.routers.portainer-secure.service=portainer"
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"
      - "traefik.http.routers.portainer-secure.tls.certresolver=letsEncrypt"             
      - "traefik.docker.network=proxy"

networks:
  proxy: # this is the network provided by traefik
    external: true
  backend: 
    external: false

volumes:
    db-data:
        external: false  